"""Localization types, adapters, metrics, consensus, student, and benchmark harness."""

from cvi.localization.adapters import (
    AbstractLocalizationAdapter,
)
from cvi.localization.benchmark import (
    ap10k_body17_pose_summary,
    build_contact_sheet,
    run_benchmark,
)
from cvi.localization.consensus import (
    ConsensusDogInstance,
    FailureVector,
    compute_error_correlation,
    consensus_admission,
    consensus_dog_bbox,
    consensus_dog_instances,
    consensus_keypoint,
    robust_weighted_keypoint,
    weighted_box_fusion,
)
from cvi.localization.quality import (
    DogQuality,
    FaceQuality,
    NoseQuality,
    compute_iou,
    detection_average_precision,
    detection_summary,
    estimate_blur,
    greedy_bipartite_match,
    normalized_mean_error,
    pixel_correct_keypoint,
    score_dog_quality,
    score_face_quality,
    score_nose_quality,
)
from cvi.localization.roi import (
    expand_bbox,
    face_and_weak_nose_rois_from_pose,
    face_roi_from_dog,
    is_truncated,
    square_padded_crop,
    square_padded_crop_with_mask,
)
from cvi.localization.student import AbstractStudentTrainer, TeacherLabel
from cvi.localization.types import (
    AP10K_BODY_17_KEYPOINT_NAMES,
    AP10K_BODY_17_SCHEMA,
    DetectionBox,
    Keypoint,
    KeypointSet,
    LocalizationBenchmarkEntry,
    LocalizationResult,
)

__all__ = [
    "AbstractLocalizationAdapter",
    "AbstractStudentTrainer",
    "AP10K_BODY_17_KEYPOINT_NAMES",
    "AP10K_BODY_17_SCHEMA",
    "ConsensusDogInstance",
    "DetectionBox",
    "DogQuality",
    "FaceQuality",
    "FailureVector",
    "Keypoint",
    "KeypointSet",
    "LocalizationBenchmarkEntry",
    "LocalizationResult",
    "NoseQuality",
    "TeacherLabel",
    "build_contact_sheet",
    "ap10k_body17_pose_summary",
    "compute_error_correlation",
    "compute_iou",
    "consensus_admission",
    "consensus_dog_bbox",
    "consensus_dog_instances",
    "detection_average_precision",
    "consensus_keypoint",
    "detection_summary",
    "estimate_blur",
    "expand_bbox",
    "face_roi_from_dog",
    "face_and_weak_nose_rois_from_pose",
    "greedy_bipartite_match",
    "is_truncated",
    "normalized_mean_error",
    "pixel_correct_keypoint",
    "robust_weighted_keypoint",
    "run_benchmark",
    "score_dog_quality",
    "score_face_quality",
    "score_nose_quality",
    "square_padded_crop",
    "square_padded_crop_with_mask",
    "weighted_box_fusion",
]
